name: design_diario
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  string_validator: ^1.0.0
  flutter_screenutil: ^5.6.1
  dartz: ^0.10.1



  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  dio: ^5.3.0
  firebase_auth: ^4.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

 
  assets:
    - assets/images/

