// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_xX_lx7ejqTWtJNoTstzUNhGaKi8ARuo',
    appId: '1:128063007485:web:0513829213bd36e867ac94',
    messagingSenderId: '128063007485',
    projectId: 'design-diario',
    authDomain: 'design-diario.firebaseapp.com',
    storageBucket: 'design-diario.appspot.com',
    measurementId: 'G-61H8N6EHD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTALDTMZ6b4yzVxQMONFbYNmFSJM4uxgY',
    appId: '1:128063007485:android:2f4389179557c78767ac94',
    messagingSenderId: '128063007485',
    projectId: 'design-diario',
    storageBucket: 'design-diario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZeJ00P6VRydqWnhVzhCxfnyiAxZE1QL8',
    appId: '1:128063007485:ios:746bfaa865cacc1867ac94',
    messagingSenderId: '128063007485',
    projectId: 'design-diario',
    storageBucket: 'design-diario.appspot.com',
    iosClientId: '128063007485-gll8ufkk9morva2tb6o928k7kvvgnoh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.designDiario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZeJ00P6VRydqWnhVzhCxfnyiAxZE1QL8',
    appId: '1:128063007485:ios:bcde8cd354878cc067ac94',
    messagingSenderId: '128063007485',
    projectId: 'design-diario',
    storageBucket: 'design-diario.appspot.com',
    iosClientId: '128063007485-m9bvp5e00a2caa0kjc42atvh5sajfvbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.designDiario.RunnerTests',
  );
}
